In [ ]:
import numpy as np

# ４章　線形代数

## ４．１　ベクトル

ベクトル、スカラー

### ゼロから作る方法としてベクトルを数値のリストとして表現するのが最もかんたんです。

In [3]:
height_weight_age = [ 70, #身長
                     170, #体重
                     40]  #年齢

height_weight_age

[70, 170, 40]

### ベクトルの和　差は省略

In [28]:
def vector_add(v,w):
    """対応する要素の和"""
    return [v_i+w_i for v_i, w_i in zip(v,w)]


v1 = np.random.randint(0, 10, 5)
w1 = np.arange(5, 15, 2)

print(v1)
print(w1)

res1 = vector_add(v1, w1)

print(res1)

print(np.shape(v1))

print(np.shape(res1))


[5 9 7 9 4]
[ 5  7  9 11 13]
[10, 16, 16, 20, 17]
(5,)
(5,)


### 要素ごとの和を求める (reduce)

In [62]:
def vector_sum(vectors):
    """対応する要素の総和"""
    result = vectors[0]
    print("res:", end="")
    print(result)
    for vector in vectors[1:]:
        print("vec:", end="")
        print(vector)
        result = vector_add(result, vector)   #vector_add()を使う
        print("res:", end="")
        print(result)
    return result


v1 = np.random.randint(0, 10, (3,4))
print("入力")
print(v1)
print("-------------")

v2 = vector_sum(v1)

print("出力")
print(v2)
print("------------------------------------------")

v3 = np.random.randint(0, 10, (2,3,4))
print("入力")
print(v3)
print("-------------")

v4 = vector_sum(v3)
print("出力")
print(v4)


入力
[[3 4 1 6]
 [9 8 1 4]
 [6 2 5 7]]
-------------
res:[3 4 1 6]
vec:[9 8 1 4]
res:[12, 12, 2, 10]
vec:[6 2 5 7]
res:[18, 14, 7, 17]
出力
[18, 14, 7, 17]
------------------------------------------
入力
[[[6 3 3 0]
  [7 5 0 4]
  [2 4 7 9]]

 [[5 5 5 5]
  [0 0 7 0]
  [5 0 7 2]]]
-------------
res:[[6 3 3 0]
 [7 5 0 4]
 [2 4 7 9]]
vec:[[5 5 5 5]
 [0 0 7 0]
 [5 0 7 2]]
res:[array([11,  8,  8,  5]), array([7, 5, 7, 4]), array([ 7,  4, 14, 11])]
出力
[array([11,  8,  8,  5]), array([7, 5, 7, 4]), array([ 7,  4, 14, 11])]


### partialを使った書き方　線形代数ではなくpythonの話ですが少し以下に記載


functools.reduce(function, iterable)  
２引数のfunctionをiterableの要素に対して左から右に累積的に適用し、iterableを単一の値に縮約します  

functools.partial  
def func(param, param2)  だとして、

funcnew = functools.partial(func, param)とすると  

funcnew(param2)とすると、 func(param, param2)が実行される  


In [58]:
import functools as ft
vector_sum2 = ft.partial(ft.reduce, vector_add)
#->つまり、vector_sum2にあたえられたiterableは、vector_addに累積的に適用され単一の値に縮約される

v10 = np.random.randint(0, 10, (2,3,4))
print(v10)

v12 = vector_sum2(v10)
print(v12)

[[[9 9 1 9]
  [3 2 8 5]
  [7 5 0 3]]

 [[3 0 6 2]
  [8 5 2 8]
  [7 5 5 5]]]
[array([12,  9,  7, 11]), array([11,  7, 10, 13]), array([14, 10,  5,  8])]


    2×3×4が  3×4になっている
    [[[0 2 4 9],        [0 2 4 9],        [9 7 3 9]]
     [[0 8 1 1],        [5 2 0 4],        [3 5 7 8]]]
     
     [[ 0, 10,  5, 10], [ 5,  4,  4, 13], [12, 12, 10, 17]]

### ベクトルとスカラーの乗算・・・省略
### 平均値の算出・・・省略
### 内積の計算・・・省略
### マグニチュード（大きさ）の計算・・・省略

## ４．２行列
行列は数値を２次元に配置したものです。ここでは行列をリストのリストとして表現します。


In [59]:
A=[[1,2,3], [4,5,6]]
A

[[1, 2, 3], [4, 5, 6]]

行列の大きさ＝行数×列数

In [63]:
def myshape(A):
    num_rows=len(A)
    num_cols= len(A[0]) if A else 0
    return num_rows, num_cols

print(myshape(A))

(2, 3)


### 単位行列・・・対角要素が１で、それ以外が０の行列

In [73]:
def make_matrix(num_rows, num_cols, entry_fn):
    return [
               [ entry_fn(i,j) for j in range(num_cols)]
                for i in range(num_rows)]

def is_diagnonal(i,j):
    return 1 if i==j else 0

identity_matrix = make_matrix(5, 5, is_diagnonal)

identity_matrix

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

p.64  
・n × k行列は、k次元のベクトルからn次元のベクトルへの写像を行う線形関数とみなすことが可能です  
・行列は２項関係を表現するのにも使えます  
    例　ネットワークの接続情報を行列で表現する  
    A[i][j]==1・・・ネットワークのノードiとノードjが繋がっている。０なら繋がっていない  
  
下の例　friendships[0]と繋がっている番号を friends_of_zeroとして抽出する

In [77]:
friendships = [[0,1,0,1,1,0,0,0,1,0,0,0,1]]

friends_of_zero = [i #iを要素として追加する
                   for i, is_friend in enumerate(friendships[0])  # (index, value)が i, is_friendにセットされる
                   if is_friend #もし is_friendが1なら
                  ]

friends_of_zero

[1, 3, 4, 8, 12]

# ５章　統計

## ５．１　データの特徴を表す

いろんな統計量  
・データの数  
・最大値、最小値  
・２番目に大きな値、２番目に小さな値。。。  
いろいろある

### ５．１．１　代表値

・平均値  
・中央値  
・分位数・・・上位からx%の位置にある値  
・最頻値  

### ５．１．２　散らばり

分散＝ sigma i（Xi　ー　Xver）Xver：平均 　　

標準偏差＝分散の平方根

### ５．２　相関

共分散　系列Aのデータと、系列Bのデータの関係を表す  
共分散= sigma i （XAi-XAver）（XBi-XBver）  XAver：XAの平均、 XBver：XBの平均  
　　正か負なら相関あり、０なら相関なし  
　　値の大きさの解釈が困難(p.74の真ん中くらいの記述）  
相関係数・・・共分散をそれぞれの系列の標準偏差で割ったもの

### ５．３　シンプソンのパラドックス

東海岸のデータサイエンティストの方が友達が少ない  


実は  
PhDありの人が友達が少ない、かつ、東海岸はPhDありの人が多い　だった  

PhDありだけで調べたら東海岸の方が友達が多い    
PhDなしだけで調べても東海岸の方が友達が多い  


### ５．４　その他相関係数についての注意点


相関係数が０の場合、２つの変数には線形関係が存在しないことを示します。  
別の種類の関係があるかもしれません。

例えば  
x = [-2, -1, 0, 1, 2]  
y = [ 2,  1, 0, 1, 2]  

yはxの絶対値  
ここで欠けているのは、x_iとmean(x)を比較することで、y_iとmean(y)に関する情報が得られるという関係  

相関係数は関係がどれだけ大きいのかについては何も言及しません  

x = [-2, -1, 0, 1, 2]  
y = [99.98, 99.99, 100, 100.01, 100.02]  

yの平均と分散に関して得られる正しい情報があるが、  
yは絶対値に対して、そもそも5サンプルの分散が非常に小さいので、ほとんど変わっていないという解釈もできる  


### ５．５　相関係数と因果関係

「相関関係は因果関係ではない」  

相関があったとして、それだけでは、どっち向きかの因果関係があるかどうかは言えない  
  
ゲームをしている時間  
試験の成績  

ゲームをしている時間が長いから　試験の成績が低いのだ  
と、もし結論づけて、それが正しかったとしても、相関はそこまでは主張はしていない  



